"""Initial migration.

Revision ID: 6fa62f3534f3
Revises: 
Create Date: 2020-04-14 03:18:52.227393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa62f3534f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('lastname', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=240), nullable=True),
    sa.Column('profile_picture', sa.String(), nullable=True),
    sa.Column('date_joined', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('pid'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    # ### end Alembic commands ###
